# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_delete_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
