# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0008_auto_20170317_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='colleges',
            field=models.ManyToManyField(null=True, related_name='College', to='collection.College'),
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ManyToManyField(null=True, related_name='Hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
