# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0010_auto_20170317_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='colleges',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
