# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20170317_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to='collection.College'),
        ),
    ]
