# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_hospital_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
    ]
