# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=255)),
                ('collegeAddress', models.CharField(max_length=255)),
                ('collegeTown', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='College', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=255)),
                ('hospitalAddress', models.CharField(max_length=255)),
                ('hospitalPhoneNumber', models.CharField(max_length=255)),
                ('hospitalDirections', models.CharField(max_length=255)),
                ('college', models.ManyToManyField(to='webPortal.College')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
