# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0006_hospital_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='college',
        ),
        migrations.AddField(
            model_name='hospital',
            name='college',
            field=models.ManyToManyField(null=True, related_name='College', to='webPortal.College'),
        ),
    ]
