# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPortal', '0007_auto_20170320_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='college',
        ),
        migrations.AddField(
            model_name='college',
            name='hospital',
            field=models.ManyToManyField(null=True, related_name='Hospital', to='webPortal.Hospital'),
        ),
    ]
